name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
  lint:
    name: Lint and test - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Lint files
      run: npm run lint
    - name: Run tests
      run: npm test
